import type { Metadata } from "next";
import "./globals.css";

// TODO: Font Customization
// Current: Using Apple's SF Pro system fonts
// To customize fonts later:
// 1. Import Google Fonts: import { Inter, JetBrains_Mono } from "next/font/google";
// 2. Create font objects with variable names
// 3. Add to body className
// 4. Update CSS variables in globals.css

// Apple SF Pro system fonts - automatically uses SF Pro on Apple devices
// Falls back to system fonts on other platforms
const appleFonts = {
  sans: "--font-apple-sans",
  mono: "--font-apple-mono",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${appleFonts.sans} ${appleFonts.mono} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
